export default function FAQStructuredData() {
  const faqData = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What are daily affirmations?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Daily affirmations are positive statements that you repeat to yourself to challenge and overcome negative thoughts. They help reprogram your subconscious mind, boost self-confidence, and create a more positive mindset. Research shows that regular practice of affirmations can reduce stress and improve mental wellbeing.',
        },
      },
      {
        '@type': 'Question',
        name: 'How do I use affirmations effectively?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'To use affirmations effectively: 1) Practice them in the morning when your mind is most receptive, 2) Say them out loud with conviction, 3) Use present tense "I am" statements, 4) Be consistent and repeat daily, 5) Choose affirmations that resonate with your personal goals. Combining affirmations with visualization and deep breathing enhances their effectiveness.',
        },
      },
      {
        '@type': 'Question',
        name: 'Do affirmations really work?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: "Yes, research supports that affirmations work. Studies using MRI scans show that self-affirmation activates the brain's reward centers. A study published in Social Cognitive and Affective Neuroscience found that affirmations can help reduce stress and improve problem-solving abilities. The key is consistent practice and choosing affirmations that feel authentic to you.",
        },
      },
      {
        '@type': 'Question',
        name: 'What categories of affirmations are available?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Daily Affirmations offers six categories: General (everyday positivity), Career (professional success and workplace confidence), Relationships (love and connection), Health (mental and physical wellbeing), Personal Growth (self-development and transformation), and Confidence (self-esteem and self-worth). Each category provides targeted affirmations for specific life areas.',
        },
      },
      {
        '@type': 'Question',
        name: 'Are the affirmations generated by AI?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes, Daily Affirmations uses AI technology to generate unique, personalized affirmations. Each time you click "Generate New," the AI creates a fresh affirmation tailored to your selected category. This ensures you receive varied, meaningful affirmations rather than seeing the same ones repeatedly.',
        },
      },
      {
        '@type': 'Question',
        name: 'Is Daily Affirmations free to use?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes, Daily Affirmations is completely free to use. There is no registration required, no subscription fees, and no hidden costs. You can generate unlimited affirmations across all categories and share them with others at no charge.',
        },
      },
    ],
  }

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(faqData) }}
    />
  )
}
